# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef56ba978b79af766e0527cbde3aad8e7d0e761529107f4286579a0c89c0309a1e9b9a406deefe411ddd14d2ff28a0d45395496f441aa7b1ca7c251d2ed8bf6e

test:
  secret_key_base: 2496c8bede825c5dac687567851fe79a702b2f11d87a0c48f079ad60a996206c2547d2ee4b614a77267e2e928110fdd20565778699783a9aa3fa2b812d605a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
